### ISSUE TITLE
watchify recipe not firing update event

### ISSUE THREAD

**Issue by calvinchoy** [gulpjs/gulp#1013]
Hi all,

I copy pasted the watchify fast build recipe and ran it in my current project. The recipe bundled my javascript correctly. However, update events are not fired when I update a dependency.

If I run watchify via the cli, everything works, even the update events and recompile.

Is there anything I can check that might cause the event not firing?

**Comment by phated** [comment]
Support questions should be directed to StackOverflow.  If you find a bug with the recipe, please send a PR with and update.

**Comment by IanVS** [comment]
I have hit this same problem.  Were you able to find a solution, @calvinchoy?

**Comment by calvinchoy** [comment]
Hi IanVs,

Yeah, I found a solution by googling and stackoverflow. I am not sure if this is the right/best solution but it can be used as a temporary workaround.

The problem is probably due to a osx specific fsevent bug. Anyway, you can solve this bij enabling the poll option when calling watchify in your recipe:

```
// OSX/FSEVENTS FIX: if files are not watched, due to fsevent bug
// use polling
var b = watchify(browserify(opts), {poll:true});

By the way, I didn't have watch problems when running from the shell.

**Comment by IanVS** [comment]
Thanks, I've tried that with no dice.  I deleted my comment because I thought I had narrowed it down to a vagrant issue, but that wasn't the case.  I can touch a file and watching will execute correctly once, but never a second time.  Touching another file will also cause watched tasks to execute.  I'm really scratching my head here, but thanks for responding.  :)
