### ISSUE TITLE
encoding problems on windows

### ISSUE THREAD

**Issue by jesuslpm** [gulpjs/gulp#1037]
Please see this question on StackOverflow:

http://stackoverflow.com/questions/29830563/encoding-problems-with-gulp-on-windows

**Comment by kevva** [comment]
Add `<meta charset="utf-8">` to your `<head>`.

**Comment by jesuslpm** [comment]
That doesn't solve the problem. The page is shown the same way. Additionally, we use gulp on js and css files. No meta's are allowed there

**Comment by limdauto** [comment]
+1

I think this should be part of `gulp.src`. It uses `readFile` underneath which accepts an encoding option. I think it's reasonable to expose this option to user instead of swallowing it up. I wonder if it has ever been discussed before. Otherwise I'd love to create a PR to `vinyl-fs` to expose this option.

**Comment by contra** [comment]
@limdauto I think there is an issue open for it that nobody ever got around to

**Comment by limdauto** [comment]
@contra hey mate could you take a look? https://github.com/wearefractal/vinyl-fs/pull/66

**Comment by sindresorhus** [comment]
Closing as https://github.com/wearefractal/vinyl-fs/pull/66 were closed.
