### ISSUE TITLE
Gulp 4

### ISSUE THREAD

**Issue by hanifbbz** [gulpjs/gulp#1068]
OK, this might not look like a typical issue but it is for us. We've set up a non-trivial build system based on Gulp 3. But there are many rough edges that we have to address with extra plugins (like run-sequence). Gulp 4 promises to solve many of these problems but it's not officially released yet. In fact some of the discussions about Gulp 4 age [back to](https://github.com/gulpjs/gulp/issues/361)  half a year ago. [The 4.0 branch](https://github.com/gulpjs/gulp/tree/4.0) hasn't been updated [for almost a month](https://github.com/gulpjs/gulp/tree/4.0) now and the documentation is scarce.

I know Gulp is an open source and free project and you guys are awesome for making this. Gulp is too good to be ignored. But isn't it time for officially releasing Gulp 4 and making the community happier?

**Comment by hrach** [comment]
:+1:

**Comment by Aetet** [comment]
:+1:

**Comment by zerkalica** [comment]
:+1:

**Comment by codedsignal** [comment]
Agreed: even just some feedback as to the state of play would be really appreciated.

**Comment by KapuzenSohn** [comment]
:+1:

**Comment by raleksandar** [comment]
Came here to ask the same thing.. 
:+1:

**Comment by srcspider** [comment]
You can already use gulp 4. There aren't really many differences other then `gulp.sequence` and `gulp.parallel` so pretty much just use that.

Here's the magic incantation if you need it,
```sh
sudo npm rm gulp -g
sudo npm i gulp-cli -g
```

```sh
mkdir projekt
cd projekt
echo "{}" > package.json
npm i -S gulpjs/gulp.git#4.0
touch gulpfile.js
```

---

Honestly though I don't think it should be released in it's current state.

I've been using it for a short while and there are a few things that are kind-of not the greatest, using functions everywhere isn't particularly great (forgot what it was but ended up using `gulp.task` after a while)

The syntax can be pretty verbose,
```js
gulp.task('default', gulp.series (
	'clean',
	gulp.parallel (
		gulp.series(gulp.parallel('css', 'css:tests'), 'watch:css'),
		gulp.series('assets', 'watch:assets'),
		'watch:js'
	)
));
```
You can make it less verbose,
```js
var series = gulp.series.bind(gulp);
var parallel = gulp.parallel.bind(gulp);

gulp.task('default', series (
	'clean',
	parallel (
		series( parallel ('css', 'css:tests'), 'watch:css' ),
		series( 'assets', 'watch:assets' ),
		'watch:js'
	)
));
```
But you should really be able to write arrays everywhere where you want series, and parallel should be more independent as a function.
```js
var parallel = require('gulp/parallel');

gulp.task('default', [
	'clean',
	parallel (
		[ parallel ('css', 'css:tests'), 'watch:css' ],
		[ 'assets', 'watch:assets' ],
		'watch:js'
	)
]);
```

The output isn't necessarily very clear either,

```sh
Starting 'default'...
Starting 'clean'...
Finished 'clean' after 49 ms
Starting 'parallel'...
Starting 'series'...
Starting 'series'...
Starting 'watch:js'...
Starting 'parallel'...
Starting 'assets'...
Starting 'css'...
Starting 'css:tests'...
Starting 'images'...
Starting 'webp'...
Finished 'css:tests' after 822 ms
Finished 'images' after 878 ms
Finished 'css' after 1.01 s
Finished 'parallel' after 1.06 s
Starting 'watch:css'...
Finished 'webp' after 1.99 s
Finished 'assets' after 2.04 s
Starting 'watch:assets'...
...
```
The series and parallel calls there are useless, since you cant even tell which one it is.

4.0 as I understand it is also suppose to have a repository system for task management, [to avoid doing it though other means](https://www.npmjs.com/package/hel), but I'm not sure if that's even done.

**Comment by hrach** [comment]
> I've been using it for a short while and there are a few things that are kind-of not the greatest

That will be true all the time. It's common problem of software development, "it's not perferect yet" - but it never will be.

**Comment by contra** [comment]
People keep asking us to release 4.0 as-is and simply put we aren't going to do it until it's finished. There are still fundamental issues that need to be worked out with the new stuff and we don't want to tell people that this is a stable release when it isn't done yet. If you want it to be released faster then report issues you have, contribute to discussion on github, and send PRs.

We have contributors who contribute whenever they can, and the open source community has also been helping, but we are all busy people and don't have a ton of spare time. I'm currently running multiple companies and traveling around the world - I'm maxed out right now. I've given @phated and others control over the 4.0 release because of this but I'm sure they have full plates with their own companies.

I'm devoting more time over the next few weeks to ship this but please stop the bullshit complaining, we are humans who have lives just like you.

**Comment by hrach** [comment]
These are relevant arguments. But it's not fair to say people not to bullshit, when you [tweet](https://twitter.com/contrahacks/status/560936371012263936) "I have a cold so that today's release is delayed". This was even retweeted by official account and it is directly in contradiction to the last comment.

**Comment by contra** [comment]
@hrach and then right after that my long-term relationship ended and I got rid of my house and moved to the other side of the continent to start a new company. Again: I am also a human just like you who has a life and things that are happening you may not know about.
