### ISSUE TITLE
Task missing handler?

### ISSUE THREAD

**Issue by TGOlson** [gulpjs/gulp#1083]
I'm playing around with some ways to organize my gulp tasks, and one idea I had was to dynamically dispatch to various supporting files based on task names. Do you see any utility in exposing a `task-missing` handler, potentially similar to the way a `default` task is exposed?

```js
gulp.task('task-missing', function(taskName) {
  // do crazy dispatching or meta-task managing here
});
```

**Comment by callumacrae** [comment]
Can't you do that by having a global error handler?

**Comment by phated** [comment]
we really didn't want `default` but it is kind of necessary.  this can actually be implemented in a custom registry in gulp 4.

**Comment by contra** [comment]
@phated can you provide more info about how this can be implemented with a custom registry?

**Comment by phated** [comment]
In the custom registry, the `get` method could be written to check if a task exists in the task list and if not, call some other task that the registry author specifies (although, i think it makes more sense to be a config option instead of a task).  The `get` could even partial the missing task name into the returned function to allow the extra metadata to be passed.

**Comment by TGOlson** [comment]
:+1:

**Comment by contra** [comment]
@TGOlson If you end up with working code please post it here (better yet: publish ti as a module) so others can use it
