### ISSUE TITLE
How does gulp know if task is async?

### ISSUE THREAD

**Issue by afonsomatos** [gulpjs/gulp#1119]
When using dependencies, how does `gulp` know whether there are async operations inside a task? If I don't do async operations it finishes the moment it returns. However, if there are async operations such as `setTimeout`, it magically waits till it finishes.

```javascript
var gulp = require('gulp');

gulp.task('one', function () {
    setTimeout(function(){}, 10000); // It waits when using setTimeout
                         // Doesn't wait when there is no async 
});

gulp.task('default', ['one'], function () {
    // Done...
});
```

**Comment by callumacrae** [comment]
gulp doesn't know, in that case, but node does. How it actually does it is pretty complicated—you need to know about the event loop and queue.

Basically, node knows when it has nothing left to do, so it quits.

With your task, gulp has no idea, though: it'll tell you that "one" took like a nanosecond to finish, when it actually took ten seconds. You should use the callback so that gulp knows, too:

```js
gulp.task('one', function (done) {
    setTimeout(done, 10000);
});
```
