### ISSUE TITLE
[4.0] gulp.watch(...).on('change', fn) - fn not called when...

### ISSUE THREAD

**Issue by clintwood** [gulpjs/gulp#1131]
From the [4.0 API docs](/gulpjs/gulp/blob/4.0/docs/API.md#gulpwatchglob-opts-fn):
```js
var watcher = gulp.watch('js/**/*.js', gulp.parallel('uglify', 'reload'));
watcher.on('change', function(event) { // <-- never fires
  console.log('File ' + event.path + ' was ' + event.type);
});
```
If `gulp.watch(...)` is called, as above, with the `fn` param (i.e: **`gulp.parallel('uglify', 'reload')`**) then then event in `on(...)` is never called.  However when the watch `fn` param is not passed, as below, then `on(...)` works as advertised.
```js
var watcher = gulp.watch('js/**/*.js'/*, gulp.parallel('uglify', 'reload')*/);
watcher.on('change', function(event) { // <-- now this does fire
  console.log('File ' + event.path + ' was ' + event.type);
});
```

**Comment by nmccready** [comment]
Actually I just ran into this, and our following dependent series of watches were never fired up untill adding the done callback. (BTW this used to work without it).

```
gulp.task 'watch_vendor', (done) ->
  gulp.watch paths.bower, gulp.series 'vendor'
  done()

gulp.task 'watch_front', (done) ->
  gulp.watch rmapPaths, gulp.series 'webpack'
  done()

gulp.task 'watch_admin', (done) ->
  gulp.watch adminPaths, gulp.series 'webpackAdmin'
  done()

gulp.task 'watch_all_front', gulp.series 'watch_front', 'watch_vendor', 'watch_admin'
```

**Comment by contra** [comment]
@nmccready gulp 4 removed synchronous tasks, you have to call the callback now. Your problem is unrelated to this ticket

**Comment by nmccready** [comment]
@contra I think your making an assumption as I did not present enough detail as there is no synchronous task going on here. 

Originally the code was:

```
gulp.task 'watch_vendor',  ->
  gulp.watch paths.bower, gulp.series 'vendor'

gulp.task 'watch_front',  ->
  gulp.watch rmapPaths, gulp.series 'webpack'

gulp.task 'watch_admin',  ->
  gulp.watch adminPaths, gulp.series 'webpackAdmin'

gulp.task 'watch_all_front', gulp.series 'watch_front', 'watch_vendor', 'watch_admin'
```

Where the problem was only 'watch_front' task was being called with none of the other watches being kicked off via watch_all_front. When I added in the done callback this worked as a work around for our purposes getting our code back in a working state. 

However I agree with you as I should not have to do this as it was previously not needed; and the above code was working fine.

**Comment by nmccready** [comment]
I'll take a look at this code and see if I can contribute to this project.

**Comment by heikki** [comment]
@nmccready You are accidentally returning EventEmitter objects from your tasks.

```js
gulp.task('watch_vendor', function() {
  return gulp.watch(paths.bower, gulp.series('vendor'));
});

gulp.task('watch_front', function() {
  return gulp.watch(rmapPaths, gulp.series('webpack'));
});

gulp.task('watch_admin', function() {
  return gulp.watch(adminPaths, gulp.series('webpackAdmin'));
});

gulp.task('watch_all_front', gulp.series('watch_front', 'watch_vendor', 'watch_admin'));
```

> gulp.watch returns an EventEmitter object which emits change events with the gaze event:

https://github.com/gulpjs/gulp/blob/4.0/docs/API.md#fn-1

**Comment by nmccready** [comment]
@heikki thanks!

**Comment by clintwood** [comment]
@contra, I see you closed this, does this mean the original issue is resolved (most of the other comments are not related to the OP)?

**Comment by contra** [comment]
@clintwood I don't think it was an issue to begin with, I think the cause was unrelated. I just checked glob-watcher as well and the code is dead simple https://github.com/wearefractal/glob-watcher/blob/master/index.js#L10

Emit the change event, then call the provided function from the user if it exists.

**Comment by clintwood** [comment]
@contra, that's weird I just checked again and you're right.  Thanks for your time!  I may have had an early version from 4.0 branch...
