### ISSUE TITLE
Mockups for new task display

### ISSUE THREAD

**Issue by phated** [gulpjs/gulp#1294]
This issue was spawned by https://github.com/gulpjs/gulp-cli/issues/39

Now that we have `--tasks-simple` and `--tasks-json` for tools to consume, we can re-envision what the output of `--tasks` can be.

I'd like some people to produce mockups for new display output of the task listing flag.

Things that must be supported in the mockup:
1. Display top level tasks prominently
2. Display nested task dependencies to all depths
3. Display the description next to each top level task but not on nested tasks
4. Display a list of flags for each top level task

**Comment by tylersticka** [comment]
Hi, @phated! I'm more of a designer than a developer, so my understanding of what is or isn't possible in the CLI may be lacking, but I was reading up on Gulp 4 this evening, stumbled across this issue and figured I'd throw a mockup into the mix.

I have two variations. The first one was inspired by @chmontgomery's screenshot from gulpjs/gulp-cli#39. I liked how the detailed list was able to stand on its own, slightly apart from the normal Gulp messages. That said, I missed the "tree" characters for denoting hierarchy, and I also wanted the flags to be visually distinct from the task names. So this was my first pass:

![gulp-tasks-2015-11-05-001](https://cloud.githubusercontent.com/assets/69633/10989260/eff95822-83f9-11e5-930c-2eb37fe7c11b.png)

I liked this fine, but I kind of missed the old layout... the lack of an _initial_ branch of the tree makes it a little more difficult to scan the topmost task names. And while I liked treating all the tasks consistently, I'm not sure it was successfully displaying the topmost tasks prominently.

So I brought it closer to what's there already, and since I was no longer relying on the blue to unify the tasks, played a bit more with using different colors to make the top-level tasks (and their flags) stand out:

![gulp-tasks-2015-11-05-002](https://cloud.githubusercontent.com/assets/69633/10989321/b01a75e6-83fa-11e5-8432-c92dca3dfa2e.png)

No hard feelings if these miss the mark somehow! I :heart: Gulp and will happily continue using it regardless.

**Comment by noderat** [comment]
I think it looks amazing and very informative, good work!

**Comment by phated** [comment]
@tylersticka wow, that 2nd one is amazing!  I will definitely be taking a look into implementing that design in the CLI.  Thank you so much.

**Comment by Romanx** [comment]
:+1: for the second too. Good work @tylersticka!

**Comment by marvinhagemeister** [comment]
The second one is amazing! @tylersticka

**Comment by tylersticka** [comment]
Thanks for the kind words! :blush:

**Comment by troch** [comment]
:+1: for the second one.

**Comment by phated** [comment]
Deferring to gulp-cli 1.2.0

**Comment by sttk** [comment]
I tried to achieve @tylersticka's  second image and finished.

**Comment by phated** [comment]
This has been released with gulp-cli 1.2.0 - documentation on custom metadata (descriptions and flags) at https://github.com/gulpjs/gulp-cli#custom-metadata

Many thanks to @sttk and @tylersticka!!!
