### ISSUE TITLE
Gulp 4: Watch only fires once when used with paths instead of globs

### ISSUE THREAD

**Issue by flying-sheep** [gulpjs/gulp#1322]
Hi, with gulp-babel and gulp 4:

```js
import gulp from 'gulp'
import babel from 'gulp-babel'

const paths = {
	main: 'client/src/main.js',
}

gulp.task('compile-main', () =>
	gulp.src(paths.main, { since: gulp.lastRun('compile-main') })
		.pipe(babel())
		.pipe(gulp.dest('client')))

gulp.task('watch', () =>
	gulp.watch(paths.main, gulp.series('compile-main')))

gulp.task('default', gulp.series('watch'))
```

this is the output:

```log
[14:52:51] Requiring external module babel-core/register
[14:52:52] Using gulpfile ~/Dev/Web/electro-pub/gulpfile.babel.js
[14:52:52] Starting 'default'...
[14:52:52] Starting 'watch'...
```

after hitting ctrl-s on the watched file once, this is added:

```log
[14:53:22] Starting 'series'...
[14:53:22] Starting 'compile-main'...
[14:53:23] Finished 'compile-main' after 119 ms
[14:53:23] Finished 'series' after 120 ms
```

but then each subsequent ctrl-s is ignored.

removing the `{ since: gulp.lastRun('compile-main') }` has no effect.

---

i know that my editor saves by writing to a tempfile and moving the tempfile to where the original file is, in order to make saves atomic in case of errors.

using a glob instead of a path fixes this, so i guess the problem is that using a path makes the watcher watch a file handle instead of the directory.

**Comment by phated** [comment]
Pinging @es128

**Comment by es128** [comment]
Seems related to https://github.com/paulmillr/chokidar/issues/237, which is caused by editor atomic save weirdness combined with watching a single file. You already happened upon the workaround solution, which is to force a watcher to be attached at the directory level by using a glob pattern (even a pattern that matches only the particular file like `[f]ile.txt` will work for this purpose). Some other potential workaround solutions discussed in the linked thread (such as enabling polling or using a different editor).

**Comment by phated** [comment]
@es128 thanks! going to close since you've outlined all that can be done and pointed to the underlying issue.

**Comment by flying-sheep** [comment]
that’s not all that can be done. gulp could e.g. automatically detect file patterns and convert them to glob patterns, like @es128 described.
