### ISSUE TITLE
gulp cache all files 

### ISSUE THREAD

**Issue by TeodorKolev** [gulpjs/gulp#1331]
When I do 
```javascript
var paths = {
  scripts: 'src/js/**/*.js',
};

gulp.task('scripts', ['clean'], function() {
  return gulp.src(paths.scripts)
    .pipe(sourcemaps.init())
     .pipe(uglify())
    .pipe(sourcemaps.write())
    .pipe(gulp.dest('build/js'));
});

gulp.watch(paths.scripts, ['scripts']);
```
and change file it, runs for all files. Is there option to watch only current file which is changed and to not uglify other .js files?

**Comment by contra** [comment]
@TeodorKolev In gulp 4.0 there is the `since` option (`since: gulp.lastRun('scripts')`) - in 3.x you can use the gulp-cached plugin

**Comment by TeodorKolev** [comment]
code example please

**Comment by contra** [comment]
@TeodorKolev I closed the issue because I answered your question. I'll explain more in depth:

- In gulp 3.x, you should use the `gulp-cached` module which will remove files from the stream that have not been changed. Code examples are on the README for that project https://github.com/contra/gulp-cached
- In gulp 4.x (installable with `npm install gulpjs/gulp#4.0`), you should use the `since` option to gulp.src which will prevent it from emitting files that haven't changed.

Using the `since` option in conjunction with the `lastRun` function, you can prevent files that haven't been changed since the last run of the task from being processed again:

```js
gulp.src('files', {since: gulp.lastRun('task name')})
```

**Comment by TeodorKolev** [comment]
amazing, don't you think this is a general issue?
