### ISSUE TITLE
Update vinyl-fs dependency

### ISSUE THREAD

**Issue by Pomax** [gulpjs/gulp#1439]
Gulp 3.9.0 uses vinyl-fs v0.3.14, which is truly ancient at this point and should get bumped up to 2.2.1 instead. Installing Gulp 3.9.0 currently makes NPM generate warnings due to dependencies that are used by the old version of vinyl-fs but are no longer being maintained.

**Comment by callumacrae** [comment]
https://github.com/gulpjs/gulp/issues/1428
https://github.com/gulpjs/gulp/issues/1363#issuecomment-152702047
https://github.com/gulpjs/gulp/pull/1295
https://github.com/gulpjs/gulp/pull/1349

**Comment by Pomax** [comment]
gulp 4 is not the version that npm pulls down when typing "npm install gulp", so: not until it's out of beta?

**Comment by phated** [comment]
@Pomax because it isn't done yet but it is stable enough to use.

**Comment by contra** [comment]
@Pomax "no longer maintained versions can literally disappear without notice, instantly breaking 3.9.0" This never happens, and the authors of gulp are also the authors of vinyl-fs - why would be purposely break our own module? If we wanted to explode our own project wouldn't it be easier to delete the whole package from npm? You're being slightly paranoid. I promise you we do not unpublish shit, and I don't even think you can anymore with the new npm package locking restrictions.

Just because it isn't using the bleeding edge version (which has problems, btw) doesn't make it obsolete or a "major bug", that's just crazy.
