### ISSUE TITLE
vinyl-fs dependency

### ISSUE THREAD

**Issue by denysvitali** [gulpjs/gulp#1587]
Hi everyone,
I just wanted to report that gulp uses an old version of `vinyl-fs` (`@0.3.0` is used, `@2.4.2` is the newest).
The problem is that vinyl-fs@0.3.0 depends on `graceful-fs@3.0.0` which is deprecated and marked as non working on the most recent versions of node.

```
dvitali ~ npm info vinyl-fs@0.3.0 dependencies
{ 'glob-stream': '^3.1.5',
  'glob-watcher': '^0.0.6',
  'graceful-fs': '^3.0.0',
  'lodash.defaults': '^2.4.1',
  'map-stream': '^0.1.0',
  mkdirp: '^0.5.0',
  'strip-bom': '^0.3.0',
  through2: '^0.5.1',
  'through2-map': '^1.3.0',
  vinyl: '^0.2.0' }
```

The following warning is thrown
`npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.`

**Comment by lebbe** [comment]
Hi, denysvitali

I came across the same issue yesterday, but found #1571. To  me it seemed obvious that it couldn't be due to a devDependency as phated claims, because, well, I get the deprecation warning on a regular npm install, and that shouldn't install devDependencies ... I didn't dare do as you did now, starting a new issue, since #1571 says in bold letters we are not allowed to. So. Kudos to you.

**Comment by denysvitali** [comment]
Same think I thought... Closing as per #1571

**Comment by lebbe** [comment]
Better to be safe and sorry! :-)

I also see another glpjs dev says to update to gulp 4 in #1537. But, as far as I can see, you are totally correct. The warning is because of a dependency to an old version of vinyl-fs, while phated claims the log warning comes from a **devDependency**. Plus he closes the possibility to comment on the issue, so we are not allowed to correct him ...

**Comment by phated** [comment]
The graceful-fs in the vinyl dependency won't be upgraded due to it being a breaking version and vinyl-fs in gulp 3.x won't be upgrade, again, because there are breaking changes.  Use gulp 4 or ignore the deprecation warning.

**Comment by denysvitali** [comment]
Thanks for the info @phated.

**Comment by morungos** [comment]
So, basically, should I gulp => npm due to this? gulp 4 isn't primary release yet, and yet gulp 3's dependency chain is broken on new node. This issue has been pending for about two years without progress or resolution and frankly that's a bit weird.
