### ISSUE TITLE
gulp says: Task never defined: default

### ISSUE THREAD

**Issue by AndrewEastwood** [gulpjs/gulp#1634]
I used the example from the readme file and, I'm getting this error: Task never defined: default

**Comment by AndrewEastwood** [comment]
the example that is written in ES2015

**Comment by phated** [comment]
You are probably using the wrong `gulp-cli` module.  You must be using the latest released version.

**Comment by AndrewEastwood** [comment]
I've got these versions:
CLI version 0.4.0
Local version 4.0.0-alpha.2

**Comment by phated** [comment]
@AndrewEastwood that is the incorrect version, as I stated above.  Use the correct verison, which can be found at https://www.npmjs.com/package/gulp-cli

**Comment by phun-ky** [comment]
I am experiencing the same issue with:

$ gulp -v
    [13:37:16] Failed to load external module @babel/register
    [13:37:16] Requiring external module babel-register
    [13:37:16] CLI version 2.0.1
    [13:37:16] Local version 4.0.0

**Comment by demurgos** [comment]
@phun-ky 
This is an old issue not related to your problem. Your problem is a configuration error, not a Gulp bug. This tracker is reserved for Gulp bugs. For support, use Stackoverflow or Gitter (see README). Your comment don't have enough context. If this is really a Gulp issue, open a separate issue and use the template issue. These rules are not against you personally but to handle the high volume of issues.

**Comment by subhadande** [comment]
This is my gulpfile.js,

var gulp = require("gulp");  
var ts = require("gulp-typescript");  
var tsProject = ts.createProject("tsconfig.json");  
gulp.task("default", function() {  
    return tsProject.src().pipe(tsProject()).js.pipe(gulp.dest("dist"))  
}); 

This is the version of gulp,
CLI version: 2.2.0
Local version: 4.0.2

But while running the command "gulp; node dist/app.js" I am getting this error 'Task never defined'

Can you please help me on this
