### ISSUE TITLE
Update liftoff version

### ISSUE THREAD

**Issue by balihoo-dengstrom** [gulpjs/gulp#1672]
2.2.1 is the current version of the [liftoff](https://www.npmjs.com/package/liftoff) dependency. Gulp is currently targeting version 2.1.0.

**Comment by phated** [comment]
I believe you are unaware of how the `^` range works in semver.  If a package depends on `^1.0.0`, it will get any update before `2.0.0` (so it would get `1.0.1`, `1.2.0` and even `1.10.25`).  Below `1.0.0` it acts differently but that's why we are trying to get all our deps to bump to `1.0.0`.  If you are reinstalling and seeing the old version, you must clear your npm cache.
