### ISSUE TITLE
[gulp 4] Any reason file changes would not be triggered after npm install?

### ISSUE THREAD

**Issue by adambuczynski** [gulpjs/gulp#1717]
I have a very simple `gulp.watch` on an array of `node_modules` packages/source files.

When I open the `node_modules` folder and edit one of the files in my text editor, the watch triggers perfectly. However, when I do an `npm install` which updates the package and changes the files as well, the watch is not being triggered.

Is there any particular reason why this would be happening?

This is with the latest Gulp 4.

**Comment by phated** [comment]
Maybe chokidar or npm does something that would cause this to behave incorrectly.  You should open it with chokidar and see if they've encountered this before.

**Comment by adambuczynski** [comment]
Well... this is the second or third issue that I've raised related to problems with `gulp.watch`, and both times they were dismissed with a similar response :( 

If gulp offers file watch functionality, then I think the gulp developers should support their user base and look into these issues a bit deeper. We, as developers using gulp, shouldn't have to care about what packages gulp uses internally for its file watching mechanics. If `gulp.watch` has problems, we report the issues here, because this is the tool we use. It shouldn't be expected of us to have to go and analyse which packages gulp chose to use internally.

Besides, whether the issues are in fact in gulp or chokidar doesn't really matter. If you as gulp use chokidar as underlying tool, then you have an interest in making sure that the tool works properly. Currently, it's not working properly and has several outstanding issues, and that in turn makes `gulp.watch` suffer from the same issues.

I feel that this approach of "not our problem" and sending people off to repositories of gulp's underlying tools is alienating developers away from gulp. For me personally, it's this lack of support and persistent bugs which don't get addressed that is driving me towards alternatives lately.

**Comment by phated** [comment]
Working on gulp is not a full time job for anyone that puts effort into it and you shouldn't expect any semblance of support (as is stated in the MIT license and shouldn't be assumed for any open source project).  We use external dependencies to provide this tool for the community and you are experiencing the typical workflow in the node world.  You are welcome to use alternatives if you think you aren't receiving the support you __deserve__.  I am locking this thread since you are just attempting to ruin any ambition the contributors of this project have remaining.

**Comment by contra** [comment]
@adambuczynski 

As @phated said multiple times (and I've done in countless other issues) - we don't do anything special for watch. We didn't write the watch stuff, and I certainly don't envy the people who did write the watch stuff because it's a hard problem to solve apparently. I don't know what "alternatives" you're talking about - if you do any file watching in node, you're using either chokidar or gaze and I can tell you chokidar is the best of the two.

You're basically blaming the car company because the cities roads have potholes.

If you have a bug with chokidar, open the bug on the chokidar repo - it isn't that complicated. We absolutely will back you up on the issue you create (I do this all the time!) and try to help in any way we can because obviously we want gulp to be good regardless of who owns what functionality. We fight battles for our users constantly to make sure everything works right, just please open your tickets on the correct repository - it's really all we're asking you to do, there's no reason to get hostile and act like we're brushing you off. 🌴
