### ISSUE TITLE
Question: Gulp 4: task composition

### ISSUE THREAD

**Issue by gamelover42** [gulpjs/gulp#1769]
I have a large build that is composed of multiple sub-projects that are all built from a central set of shared gulp scripts. 

say I want to do this (there are other modules that define the actual tasks for the sub-projects):
```
    var apps = [...]; //list of configuration objects for sub-projects in question
    function builds() {
      var buildNames = apps.map(function (app) {
        return "release-build-" + app.name;
      });
      return gulp.parallel(buildNames);
    }
    function tests() {
      var testNames = apps.map(function (app) {
        return "test-" + app.name;
      });
      return gulp.series(testNames);
    }
    gulp.task("test", tests);
    gulp.task("release-build", gulp.series(tests, builds));
```

In gulp 3 I do the following (the code for the release-build task follows the same pattern as test):

```
var runSequence = require("run-sequence").use(gulp);
  gulp.task("test", function (callback) {
    // Get the test tasks of all children
    var tasks = apps.map(function(app) {
      return "test-" + app.name;
    });
    tasks.push(callback);
    //run tasks sequentially
    return runSequence.apply(null, tasks);
  }); 
```

however when I try to run the new gulp 4 version I get the dreaded "The following tasks did not complete 'test' Did you forget to signal async completion?

How can I build my tasks names and pass them to gulp.series or gulp.parallel in gulp 4 like I did with run-sequence?

**Comment by phated** [comment]
You shouldn't be generating tasks as part of other tasks.  Your examples don't look async so I don't know why you aren't just generating the tasks at the top level.

Support questions should be directed to StackOverflow.

**Comment by trusktr** [comment]
[Pojector](https://github.com/projectorjs) is similar to Gulp, in that it is a task runner, but due to the fact that Projector tasks are defined as named exports, we can also easily import tasks and compose them, as in [this example](https://github.com/projectorjs/projector-example/blob/master/components/projector.js).

Taking that into consideration, you might find it easier to run Gulp tasks inside of Projector tasks, and compose them by simply importing them into higher-level Projector tasks like in the example. Thought I'd throw that in there, since I was looking at how to compose tasks for sub projects as well (which can be useful for monorepos).

**Comment by trusktr** [comment]
Nevermind, this is already supported by Gulp 4, thanks to exporting tasks by reference rather than defining them by name. See https://github.com/gulpjs/gulp/issues/736#issuecomment-364042189

To sum it up:

```js
// ./subproject/gulpfile.js
const gulp = require('gulp')

exports.build = function() {
  gulp.src(...)
    .pipe(...)
)
```

```js
// ./gulpfile.js (root)
const gulp = require('gulp')
const subproject = require('./subproject/gulpfile')

// task with no dependencies
function clean() {
  // ...
}
exports.clean = clean

// build task depends on clean task and subproject's build task
exports.build = gulp.series(clean, subproject.build, function() {
  // console.log('building...')
})
```
