### ISSUE TITLE
Feature request: run gulp without local copy

### ISSUE THREAD

**Issue by fheidrich** [gulpjs/gulp#1816]
Hello, I would like to be able to use gulp by installing it ONLY globally. As far as I can tell, gulp also requires it to be install in the local node_modules.

Here is my situation, I'm working on a large scale enterprise web application, this application has several independent UI components (which one has its own WAR file). Although these UIs were build at different points in time, we did a good job keeping these UIs using the same stack so that we can build them all using the same tool-chain (same gulp, same gulp-sass, same gulp-babel, same gulp-eslint, etc, huge list goes on).

What I would like is to have this entire tool-chain in a common place and use it to build all my UIs. I do need the gulpfile.js to be in the UI folder though.

In this project, and other projects in the past, I had complex build system including native, ios, android, java, etc and I never had to have the same compiler/tool-chain installed twice.

Please, allow for gulp to run just with the global copy.
Thank you

**Comment by phated** [comment]
Running from global would likely be hard to impossible because node doesn't resolve modules there.

People already solve your problem with different command line flags.  Some combination of `--cwd`, `--gulpfile`, etc.  You can probably search or ask on StackOverflow for help setting that up.

Global installs should probably be seen as an anti-pattern and everything should be local.  We have solutions for sharing tasks coming in 4.0 but nothing in 3.x.
