### ISSUE TITLE
When is gulp4 officially to be released

### ISSUE THREAD

**Issue by SetTrend** [gulpjs/gulp#1822]
Gulp4 is prerelease for more than a year.

Shouldn't it be time now to finally get it released?

**Comment by callumacrae** [comment]
> If you're asking about the status of Gulp 4, please don't! You can see the remaining issues on the gulp4 label: https://github.com/gulpjs/gulp/issues?q=is%3Aissue+is%3Aopen+label%3Agulp4

You are very welcome to contribute if you'd like it to be released quicker 😄

**Comment by dtothefp** [comment]
Understandable it's frustrating to have requests rather than PR's but would it be possible to get `4.0.0-alpha.2` published on NPM?

I've been using Gulp 4 in production since early 2016 and it gets painful for installs in Docker if I need GitHub creds.

**Comment by phated** [comment]
@dtothefp You don't need github creds to install this because it is a public project.  You need to use the https reference instead of the github reference.  We aren't release alphas for the reasons stated in https://github.com/gulpjs/gulp/issues/1486.  Please stop drudging up these old annoying threads because they just burn us out faster and will slow down the process.

**Comment by contra** [comment]
`npm install gulpjs/gulp#4.0`
