### ISSUE TITLE
Plugin Guidelines to include node 0.10/0.12 support

### ISSUE THREAD

**Issue by phated** [gulpjs/gulp#1829]
I'm going to be adding a plugin guideline that requires node 0.10 and 0.12 support.

We will be reviewing the supported versions about every 6 months, but the current recommendation from @seldo is to support node 0.10 for about another year.

**Comment by strugee** [comment]
@phated is this still the case? We're approaching one year from when this was filed

**Comment by phated** [comment]
@strugee it will be the case through the 4.0 release line.  Sorry that I haven't had the bandwidth to add it directly to the docs.

**Comment by strugee** [comment]
@phated np, I'm sure you're super busy.

By "through the release line" do you mean "all the way until the end of all maintenance"?

**Comment by phated** [comment]
@strugee anything 4.x but there's not been a decision on how long that will be (we'll need to make a decision on how close 5.0 is once 4.0 ships).

**Comment by strugee** [comment]
@phated OHHHHHHHH hahahaha 😂

Somehow I thought you were talking about Node.js 4.x? That's why I asked about the end of _all_ maintenance. That makes much more sense now; thanks for clarifying 👍

**Comment by nicolashenry** [comment]
It is 2020 and node 0.10.x and 0.12.x reach their end-of-life since more than 3 years right now: https://github.com/nodejs/Release#end-of-life-releases

When does gulp will drop support for those versions too?

From what I understand [here](https://github.com/gulpjs/glob-watcher/pull/41) and [here](https://github.com/gulpjs/glob-watcher/issues/49), I understand that this could be expected for Gulp 5 but it seems that there is not plan for this anywhere for any gulpjs package.

**Comment by phated** [comment]
1. Not everyone has the flexibility to upgrade at the speed node releases version updates.
2. Gulp is maintained by volunteers that don't have a lot of free time. We get to things when we can.
3. This was never implemented and definitely not followed by plugins anyway.
4. Just like all our project plans, V5 roadmap is at https://github.com/orgs/gulpjs/projects/4
