### ISSUE TITLE
Wrong gulp.src() behavior in Windows

### ISSUE THREAD

**Issue by ibc** [gulpjs/gulp#1847]
* gulp `4.0` branch (updated today 2-11-2016)
* Node 4.4.1

This is the problematic code:

```js
gulp.task('css', function() {
	var src = path.join('css', 'style.css');

	return gulp.src(src)
		.pipe(gulp.dest('output/'));
});
```

In OSX the task reads `css/style.css` and copies it into `output/style.css`.
However, in Windows 10 the task copies it into `output\css\style.css`.

I expect the OSX behavior to be the correct one.

**Comment by phated** [comment]
Hey @ibc, it turns out you were actually relying on bugged behavior in our underlying libraries.  Which was fixed in resolution to https://github.com/jonschlinkert/is-glob/issues/5.

Basically, we weren't supporting escape characters (the `\\` character) when determining the glob's base/parent but node-glob supported it in their glob parsing.  On Windows, node's standard lib creates paths like `C:\\home\\css\\style.css` which is not a directory in the eyes of a glob pattern.  Instead, the pattern must look like `C:/home/css/style.css`.  When you use `path.join` on Windows, it creates a path separated by `\\` which won't work now that we fixed the escaping bug.

My recommendation is to just avoid `path.join` or any other `path.*` utility methods.  You can just do `var src = 'css/styles.css'` and we figure everything out just fine.  If you need to use the `path.*` utilities for some reason, you can use `path.posix.*` on newer versions of node or use the [path-posix](https://www.npmjs.com/package/path-posix) module on npm.

**Comment by ibc** [comment]
Clear. Thanks a lot.
