### ISSUE TITLE
README Explanation

### ISSUE THREAD

**Issue by talonbragg** [gulpjs/gulp#1902]
This tracker is for bug reports only.

Before opening an issue, please make sure you've checked the following:

- For support requests, please use Stack Overflow (stackoverflow.com) or Gitter (see the README).

- If the bug is in a plugin, open an issue on the plugin repository, not the gulp repository.

- If you're getting a deprecated module warning, don't worry about it: we're aware of it and it's not an issue. To make it go away, update to Gulp 4.0.

- If you're asking about the status of Gulp 4, please don't! You can see the remaining issues on the gulp4 label: https://github.com/gulpjs/gulp/issues?q=is%3Aissue+is%3Aopen+label%3Agulp4

----

**What were you expecting to happen?**
I think that it should explain what gulp does in the README on [NPM](https://npmjs.org/package/gulp).
**What actually happened?**
It just says **This file will give you a taste of what gulp does.** This doesn't really explain it. Some people can be beginners, I thought that people would think of this in a better way if you explained it more. Some people, like me, are to lazy to read the whole file that you put there. Thank you, Talon

**Comment by bravecow** [comment]
Okay... So... when Gulp 4 will be released? 🎉 🎉 🎉

**Comment by snewell92** [comment]
@talonbragg The gulp npm page says:

> What is gulp?
> 
> Automation - gulp is a toolkit that helps you automate painful or time-consuming tasks in your development workflow.
> Platform-agnostic - Integrations are built into all major IDEs and people are using gulp with PHP, .NET, Node.js, Java, and other platforms.
> Strong Ecosystem - Use npm modules to do anything you want + over 2000 curated plugins for streaming file transformations
> Simple - By providing only a minimal API surface, gulp is easy to learn and simple to use

That seems like a pretty good definition to me. You can copy pasta the code and run it instead of reading it, adding files to fix any errors you may run into and inspect the output. It might need to say like "Run `gulp` to execute the default task" if you don't know how to run it, but that is just a google away.

This way you're not really reading the whole file, your trying to use it and learning by doing. That's how I usually do stuff.

But, that being said, you should read the "What is gulp?" section - if you don't think that gives a good enough definition maybe suggest some ways to refine it?

As it stand I think the npm page is fine. And you can easily get to the [getting started page](https://github.com/gulpjs/gulp/blob/master/docs/getting-started.md) to get all details you need (just two clicks away from npm packge's page. Click on current documentation, then click on getting started).

I vote to close this.

**Comment by contra** [comment]
This exists in the README already - not sure I get what you mean. The entire top section explains what it is and what it does, how it works, etc.
