### ISSUE TITLE
gulp.src order is wrong

### ISSUE THREAD

**Issue by steelywing** [gulpjs/gulp#1923]
This does not match file `bad` in Windows.
```
var gulp = require('gulp');

gulp.src(['!b*', 'bad'])
    .pipe(gulp.dest('out/'));
```

**What version of gulp are you using?**
gulp@3.9.1

**Comment by phated** [comment]
None of the core developers have Windows. You are going to give us more here.

**Comment by steelywing** [comment]
In Linux, also wrong result

```
user@ubuntu:~$ ls test
bad
user@ubuntu:~$ cat test.js
var gulp = require('gulp');

gulp.src(['!test/b*', 'test/bad'])
    .pipe(gulp.dest('out/'));

user@ubuntu:~$ node test.js
user@ubuntu:~$ ls out
user@ubuntu:~$ 
```

Nothing output.

**Comment by phated** [comment]
This has been fixed in gulp 4 to work like the docs describe.  This was never intended to work for gulp 3.x (I've found after digging through dependency source).  If we need to change the docs until release, that's probably the best course to take because we aren't shoving some changes between really old versions of our dependencies.
