### ISSUE TITLE
Deprecating gulp.run no longer allows defining logic before running tasks.

### ISSUE THREAD

**Issue by timrwood** [gulpjs/gulp#193]
Given a gulp file similar to the one below, before version `3.5` I was able to run some logic before running other tasks.

``` js
var shouldMinify = false;

gulp.task('js', function () {
    return gulp.src('./js/*.js')
        .pipe(concat('app.js'))
        .pipe(gulpif(shouldMinify, uglify()))
        .pipe(gulp.dest('js'));
});

gulp.task('develop', function () {
    shouldMinify = false;
    gulp.run('js');
});

gulp.task('build', function () {
    shouldMinify = true;
    gulp.run('js');
});
```

As `gulp.run` is now deprecated, the only way to have a task run other tasks is by specifying them as dependencies. This feels extremely limiting, as the only way to set some logic before running a task is by using command line flags like in [this example](https://github.com/gulpjs/gulp/blob/master/docs/recipes/pass-params-from-cli.md).

I may have missed it in the issues, but are there plans for programmatically starting tasks other than adding them as dependencies of other tasks?

**Comment by carlodicelico** [comment]
@raDiesle I had this problem at work recently. We have 4 large code bases that all need to use the same gulp tasks but with different configs (paths, etc.). What we did is turn all of our gulp tasks into a private npm module which we then install in each project. This way, we can maintain our tasks from one repo and all we have to update per project is our settings file. Our solution works equally well from the command line and from our Jenkins build scripts and we're able to provide a nicer CLI to the gulp tasks for developers.

```sh
bin/
    yourmodule
lib/
    main.js
modules/
    gulp-related node modules
tasks/
    gulp tasks
test/
    main.js
gulpfile.js
package.json
README.md
```
We also make use of gulp-load-plugins and require-dir to make all of this more modular.

**Comment by paislee** [comment]
I found this thread useful for understanding the nature of Gulp: what it is, isn't, and the power of Orchestrator. Wrote about it: http://paislee.io/a-healthy-gulp-setup-for-angularjs-projects/.

**Comment by JasonGoemaat** [comment]
"gulp is not a task runner" - Well, that is pretty much what I use it as.  There is tooling support in a lot of editors that will let you pick a 'task' from a gulpfile (vim, sublimetext, vscode, ...).  It's nice because you can just drop a gulpfile in and create named tasks in JS and easily execute them from the command line or from your editor.  I use other tools for the actual building, but I use gulp to call them.  Why?  They don't have a task running system like gulp does.  Not being able to run one task from another seems like a silly limitation to me.

For now I'm having to do a bunch of refactoring because I like it as a task runner, so I end up with methods like this:

    function buildDist(done) {
      ...
      done();
    }
    gulp.task("build-dist", ["clean-dist"], buildDist);`

**Comment by contra** [comment]
Just to be clear: the new task system in 4.0 is leagues ahead and much more flexible than the 3.x one discussed in this thread. Check out the docs on the 4.0 branch, you'll all love it!
