### ISSUE TITLE
TypeError: Invalid Version: https://registry.npmjs.org/gulp/-/gulp-3.9.1.tgz

### ISSUE THREAD

**Issue by s-a** [gulpjs/gulp#1972]
node -v
v8.0.0

I get this message after upgrading node.

**Comment by phated** [comment]
Use the search.

**Comment by gms1** [comment]
Sometimes a successful search is prevented by premature locking issues 

I stumbled upon the same issue on a clean travis build:
https://travis-ci.org/gms1/node-async-context/builds/241440316
and in my case removing the package-lock.json did the trick

**Comment by dperezmavro** [comment]
@phated you could actually be more helpful and link to the solution, if you know where it is.

**Comment by dperezmavro** [comment]
What I did to resolve the issue is combine @gms1 's solution with the one found in issue [#1967](https://github.com/gulpjs/gulp/issues/1967). To sum up,

1. Run `npm rebuild node-sass`
2. Remove `node_modules` and package-lock.json
3. Run `npm install`

And then my gulp built worked. I'm on node 8.1.0 and npm 5.0.4.

**Comment by teliapp** [comment]
It's said to be a problem of newest npm being broken. 

Installing gulp locally in the current directory solves it for it.  
Go into the directory of your project. 
sudo npm install gulp
no -g tag.

If you are working on multiple projects, oh well...

**Comment by mojoaxel** [comment]
duplicate of #1967

**Comment by Kimtn129** [comment]
@gms1 Thank you very much. Your solution is safe my life. I was fucking waste 2 hours for this problem
