### ISSUE TITLE
Time is not colored properly in console

### ISSUE THREAD

**Issue by kayo5994** [gulpjs/gulp#2098]
**What were you expecting to happen?**

When I pass the `--no-color` flag, I expect the output to be in black and white.

**What actually happened?**

The time was still in gray. (see the attached screenshot)

It looks like the package color some of the logs using terminal-specific special characters.This is fine most of the time, but when I try to print them in non-terminal context (such as a webview), I see weird characters being inserted between the bracket and time characters.

**Please post a sample of your gulpfile (preferably reduced to just the bit that's not working)**

N/A

**What version of gulp are you using?**

Version 4.0

**What versions of npm and node are you using?**

Node v.7.8.0
npm v5.6.0

![image](https://user-images.githubusercontent.com/2270639/35043086-2f0c5b4a-fbc6-11e7-9a2c-ca4610e82a82.png)

**Comment by demurgos** [comment]
This is caused by `gulp-cli`. Here is for example the code responsible for the first line:

https://github.com/gulpjs/gulp-cli/blob/1b801881aa8c12fc1c74fb76ff6f297561e6f283/lib/versioned/%5E4.0.0/index.js#L76

```
log.info('Using gulpfile', ansi.magenta(tildify(env.configPath)));
```

Here, `ansi` is implemented in `gulp-cli` and checks for the color option, but `log` is imported from `gulplog`. `gulplog` sends events that are caught by the handler [attached here](https://github.com/gulpjs/gulp-cli/blob/e5fdefb29e65c441ada61ba8308adec4f045c53f/index.js#L65). This handler is responsible to sending the logs to the console using `fancy-log`. `fancy-log` prefixes the messages with a timestamp [here](https://github.com/js-cli/fancy-log/blob/master/index.js#L30). But it normally also checks for the `no-color` so I am not yet sure what is the issue.

**Comment by demurgos** [comment]
I wrote my message at the same time as you submitted your PR. The issue is caused by an older version of `fancy-log` ([before this commit](https://github.com/js-cli/fancy-log/commit/ae67265b65cbe53834bdac1156543879e05756bf)) that did not check for the `no-color` flag.

**Comment by kayo5994** [comment]
Thanks.

**Comment by phated** [comment]
You just need to update your dependencies.  If you've recently reinstalled, you might not be getting the newest versions of all your dependencies due to npm forcing `package-lock.json` onto you by default.
