### ISSUE TITLE
Unit testing Gulp tasks

### ISSUE THREAD

**Issue by branpar** [gulpjs/gulp#2120]
Hello,

My company currently uses Gulp for the front-end builds and is a critical part of this process. Because of this I want to extent our unit testing efforts to our Gulp tasks to ensure these tasks are working properly when people make updates to them.  I am using the Webpack, Mocha, Sinon, Chai, Istanbul, Karma technology stack and am having a difficult time getting the ability to test Gulp.

My initial research points to Gulp (and many of the other modules required for these Gulp tasks) not being marked as "browser" environment and therefore not being read properly. I know that Gulp task testing isn't something that's widely done but at the enterprise level it should be so I was wondering if anyone could point me in the right direction for this effort. I've found only a few articles on the web and none of them seem to actually work.

Any help is greatly appreciated!

**Comment by doowb** [comment]
Take a look at the [gulp tests](https://github.com/gulpjs/gulp/tree/master/test).

>  not being marked as "browser" environment 

Most of gulp and the underlying libraries are used to interact with the file system. Many of the libraries that don't use the file system should be able to be bundled into something you can use in the browser, but I don't see why that should be necessary for testing tasks that build your front-end assets.

If you're going to test the gulp tasks... I'd recommend separating the task functions from the task registration so you can run the tasks directly by calling the functions. I would also use `mocha` and run them from the command line (since this is how you would run the `gulp` command).

I'm going to close this since this isn't a bug report. If you have additional questions, you should ask on Stackoverflow. Someone may have better suggestions there.

**Comment by branpar** [comment]
Thank you! This was actually incredibly helpful and was able to get me the ability to do this! I appreciate it greatly.

**Comment by phated** [comment]
Spot on @doowb!  This is actually one of the many reasons/benefits to using named functions and exports as tasks ☺️
