### ISSUE TITLE
 Received a non-Vinyl object in `dest()`

### ISSUE THREAD

**Issue by johnnyWalnut** [gulpjs/gulp#2151]
I try to use gulp.series as the following line:
```gulp.task('subtask:e2e-dist', gulp.series('subtask:webdriver-update', 'subtask:e2e-system', 'subtask:e2e-system2'));```

I expected the subtask:e2e-system2 to run after subtask:e2e-system finishes, but 
the following error is printed:

```[15:09:16] Finished 'subtask:e2e-system' after 26 s
     [15:09:16] Starting 'subtask:e2e-system2'...
/Users/yianiswalnut/Documents/5/camp/node_modules/gulp/node_modules/vinyl-fs/lib/dest/prepare.js:16
      return cb(new Error('Received a non-Vinyl object in `dest()`'));
                ^
Error: Received a non-Vinyl object in `dest()`
```
that is happening with the ```gulp: github:gulpjs/gulp#4.0```
but it works with gulp: ```git://github.com/gulpjs/gulp.git#6d71a658c61edb3090221579d8f97dbe086ba2ed```

npm: 5.6.0
node: v8.9.4

**Comment by demurgos** [comment]
This does not look like a Gulp issue but a configuration error.

The hash you posted corresponded to an alpha version of Gulp 4 not ready for production. One of the changes since this version and the stable release of Gulp 4 was the update of the Vinyl dependency. I am not sure about the details but it may be related and have stricter requirements for files piped to `dest`.

Could you post your `subtask:e2e-system2` task? Make sure that this task pipes Vinyl files to dest (usually created by `gulp.src`).
