### ISSUE TITLE
Add option for `gulp.watch` to ignore task errors

### ISSUE THREAD

**Issue by th0r** [gulpjs/gulp#216]
I have this `styles.app` task to compile my `*.styl` files:

```
gulp.task('styles.app', function () {
    return gulp
        .src('app/client/styles/*.styl')
        .pipe(stylus({
            use: ['nib'],
            set: util.env.production ? null : ['firebug', 'linenos']
        }))
        .pipe(gulpif(util.env.production, csso()))
        .pipe(gulp.dest('public/css/app'));
});
```

If there is some kind of error during styles compilation, `gulp-stylus` plugin throws an error...and it's ok, because I want build process to exit with non-zero code when building for production.
But for development I use `gulp.watch` to recompile styles "on the fly":

```
gulp.watch('app/client/styles/**/*.styl', ['styles.app']);
```

...and I don't want it to fail on any error in `styles.app` task.
Is there any way to do it?

**Comment by kirkstrobeck** [comment]
http://blog.ibangspacebar.com/handling-errors-with-gulp-watch-and-gulp-plumber/

**Comment by mnpenner** [comment]
@PavelGavlik I just tried your 'solution' -- it doesn't seem to work. Plumber prints the error and then the watcher dies, as usual. Can you show how you set up the watcher?

**Comment by mnpenner** [comment]
I think I finally have a working solution, thanks to @kirkstrobeck !

Here's an example:

```js
gulp.task('styles', function () {
    return gulp.src(styles, {base: '.'})
        .pipe(plumber({
            errorHandler: function(error) {
                gutil.log(
                    gutil.colors.cyan('Plumber') + gutil.colors.red(' found unhandled error:\n'),
                    error.toString()
                );
                this.emit('end');
            }
        }))
        .pipe(sourcemaps.init({
            loadMaps: false,
            debug: debug,
        }))
        .pipe(gulpif(/\.less$/,less({
            strictMath: true,
            strictUnits: true,
        })))
        // ... more pipes ...
        .pipe(plumber.stop())
        .pipe(gulp.dest('www/css'))
});
```

The error handler I copied out of the Plumber source which puts the pretty colors, then I added the `this.emit('end')` bit from Kirk's link which solves the watcher crashing issue.

**Comment by kirkstrobeck** [comment]
+1 @k88hudson

**Comment by LePetitDev** [comment]
:clap: @mnpenner

**Comment by gronke** [comment]
:+1: @k88hudson

**Comment by guategeek** [comment]
Thank you so much guys for figuring this out!

**Comment by ndbroadbent** [comment]
@mnpenner - I'm sorry but your solution seems to have the same problem as above. When running the task outside of `watch`, the error is swallowed and the process exits with a successful error code (**0**).

I feel like there is some misunderstanding in this thread. One reason that we need the non-zero exit code is for when you're running a `gulp` command in a CI environment, as a check to make sure that everything can be compiled without errors. In that case you want your build to fail, but if you swallow the errors with any of the solutions above, your CI service will assume that everything has passed.  So we only want to ignore errors during `watch`, and crash normally otherwise.

On the other hand, it's very annoying that I need to restart `gulp watch` whenever I have a syntax error in my source files. I could use `until gulp watch; do; sleep 1; done`, but it's not the best solution.

@contra - I'm running gulp `3.9.0`, and my `gulp.watch` task is still crashing on errors.

@r3mi - Thanks, your workaround is the only one that worked for me so far (although it's a bit of a hack, and I have to add that line to every command that might throw an error.)

Finally, just to clarify the behaviour that we're looking for:

#### Inside `watch` - handles any errors without crashing:

```
$ gulp watch
[15:52:01] Using gulpfile ~/code/example/gulpfile.js
[15:52:01] Starting 'watch'...
[15:52:01] Finished 'watch' after 32 ms
[15:52:03] Starting 'styles'...
[15:52:03] Starting 'templates'...
[15:52:03] Finished 'templates' after 91 ms
[15:52:03] Starting 'scripts'...
[15:52:03] Finished 'styles' after 273 ms
[15:52:03] Finished 'scripts' after 223 ms
[15:52:03] Plumber found unhandled error:
 /Users/ndbroadbent/code/example/login.coffee:19:1: error: unmatched }
}
^
[15:52:10] Starting 'styles'...
[15:52:10] Starting 'templates'...
[15:52:10] Finished 'templates' after 18 ms
[15:52:10] Starting 'scripts'...
[15:52:10] Starting 'templates'...
[15:52:10] Finished 'styles' after 133 ms
[15:52:10] Finished 'scripts' after 128 ms
[15:52:10] Finished 'templates' after 140 ms
[15:52:10] Plumber found unhandled error:
 /Users/ndbroadbent/code/example/login.coffee:19:1: error: unmatched }
}
^
```

#### Outside `watch` - Crashes with error and non-zero exit code:

```
$ gulp scripts
[15:54:26] Using gulpfile ~/code/example/gulpfile.js
[15:54:26] Starting 'templates'...
[15:54:26] Finished 'templates' after 74 ms
[15:54:26] Starting 'scripts'...
[15:54:27] Finished 'scripts' after 160 ms

events.js:85
      throw er; // Unhandled 'error' event
            ^
 /Users/ndbroadbent/code/example/login.coffee:19:1: error: unmatched }
}
^

$ echo $?
1
```

**Comment by contra** [comment]
@ndbroadbent You are still having the problem because this was fixed in 4.0 and you are using 3.9

**Comment by mnpenner** [comment]
@contra 4.0 doesn't appear to be out yet. npm doesn't even list a beta version. Will `watch` not crash by default, or do we need to pass it some options?

**Comment by TheunisKotze** [comment]
@contra @mnpenner I'd also like to know ^

**Comment by callumacrae** [comment]
@mnpenner @TheunisKotze You can install gulp from github to get gulp 4.0. `npm install gulpjs/gulp#4.0`

**Comment by TheunisKotze** [comment]
@callumacrae thanks, thought the question I meant was: 

> Will watch not crash by default, or do we need to pass it some options?

**Comment by noraesae** [comment]
Exactly same point here as @ndbroadbent suggested. Can't believe this thread is lasting for more than 1.5 years but still no working answer has been suggested, except for using Gulp 4.0, which hasn't been released at all.

**Comment by noraesae** [comment]
Same point with @ndbroadbent. I may just go with @r3mi 's solution until Gulp 4.0 is coming out.
