### ISSUE TITLE
Gulp file Issue : EPERM: operation not permitted,

### ISSUE THREAD

**Issue by stacksubham** [gulpjs/gulp#2207]

**Comment by demurgos** [comment]
This issue board is reserved for Gulp **bugs**. Questions (and configuration errors, third party errors) should be directed to StackOverflow or Gitter (see README.md).

This issue looks more like an error in your configuration file or in the permission settings of your OS.

If you believe this is a Gulp bug, use [the issue template](https://github.com/gulpjs/gulp/blob/master/.github/ISSUE_TEMPLATE.md). Due to the high volume of new issues, we cannot deal with invalid bug reports.
