### ISSUE TITLE
Dependencies in Gulp4

### ISSUE THREAD

**Issue by jeffrson** [gulpjs/gulp#2298]
Hi,

> This tracker is for bug reports only.

the "contributing guidelines" welcome ideas - so this may be considered rather an idea or a request for comments than a real "bug report". Nevertheless, current related behaviour appears somewhat "buggy"...

Well, apparently Gulp 4 doesn't resolve dependencies. With this gulpfile:
```
const gulp = require('gulp')

gulp.task('a', cb => {
  console.log('a')
  cb()
})

gulp.task('b', cb => {
  console.log('b')
  cb()
})

gulp.task('c', gulp.series('a', 'b', cb => {
  console.log('c')
  cb()
}))

gulp.task('d', gulp.series('a', 'b', cb => {
  console.log('d')
  cb()
}))

gulp.task('e', gulp.series('c', 'd', cb => {
  console.log('e')
  cb()
}))
```
'a' and 'b' would be run twice for task 'e'.

It had been recommended to make use of async-once (https://github.com/gulpjs/gulp/issues/2142) - otoh, this is called an "anti-pattern" in the docs https://gulpjs.org/recipes/running-tasks-in-series.html

Even if I would use async-once, I would need to resolve all those dependencies from Gulp3 (of which there may be many) manually. So, apart from the watch task mentioned in https://github.com/gulpjs/gulp/issues/2142, async-once is not a solution. Creating subtasks (like 'c:a' and 'd:a') is neither - it just doesn't fit the general case (and would be just another way of manually resolving dependencies anyway).

The usual advice when going from Gulp3 to 4 is to replace dependencies by gulp.series or gulp.parallel, but this will not work sufficiently for meta tasks like 'e', when 'c' and 'd' are needed as well. Whether or not 'a' and 'b' have side effects.

To be honest, I wonder what Gulp4 is good for, since the main task of a building system - resolving of dependencies - needs to be done by the users themselves.

Do you consider reducing tasks to those necessary?

Well, yes, in theory I could stick to Gulp3 - if it wasn't stripping BOMs of UTF8 files. Yes, I know there's a "work-around" like gulp-bom. But it's silly to reinsert BOMs which had been stripped pointlessly beforehand - especially when files are not known. They shouldn't be modified in the first place.

But, hey,  that's another sad story...

**Comment by phated** [comment]
@jeffrson please don't link unofficial documentation into our issue tracker.

The situation you describe is by design.  Implicit dependency graphs were something people felt were confusing about gulp 3, so they were removed in favor of explicit chains (it also made gulp more functional, in the process).  I'm sorry that it was a feature that you heavily relied on.

I personally wrote [async-once](https://github.com/gulpjs/async-once) as a solution for people that didn't have time to rewrite their gulpfiles to the new pattern.  While it's not the **recommended** pattern, it's also not an **anti-pattern**.  Different pieces can solve different needs.

We have official documentation now and you can find some more details at https://gulpjs.com/docs/en/getting-started/creating-tasks and https://gulpjs.com/docs/en/api/parallel#avoid-duplicating-tasks

**Comment by phated** [comment]
As for your BOM use-case, you can always pull the new vinyl-fs into a gulp3 project.  It still returns a stream so everything works together - just be aware of the breaking changes you might encounter, so please read the changelog.
