### ISSUE TITLE
`npm install gulp` installs gulp 4, not 3.9.1 as per the README up at npmjs.com

### ISSUE THREAD

**Issue by fluffynuts** [gulpjs/gulp#2318]
**What were you expecting to happen?**
To get gulp 3.9.1, which works with all the plugins I use

**What actually happened?**
I got gulp4, which completely breaks with gulp3, so my well-established build, test & deploy scripts no longer work

**Please post a sample of your gulpfile (preferably reduced to just the bit that's not working)**

```js
// this breaks with gulp4 because all the cheese has moved
// there are other examples, but this is the easiest to include here
module.exports = require('gulp-help')(require('gulp'));
```

**What version of gulp are you using?**
3.9.1

**What versions of npm and node are you using?**
node: 8.15.0
npm: 6.4.1

As a side-note: npmjs reports that the last package publish of gulp was "a year ago". Has gulp4 been abandoned? Gulp3 just worked so well and, whilst I understand the desire to re-architect, the problem, as I can see it, is that *a lot* of cheese moved and there are many gulp plugins which just don't work any more. It would be really nice if there was a compat layer -- or if gulp4 was _not_ installed with a simple `npm install --save-dev gulp`, as per the readme.

**Comment by phated** [comment]
1. Gulp 4 is our latest published version, and the npm package page reflects that. If you aren't seeing that, you may have an issue with your cache.
2. A lot of work went into making sure plugins that were written correctly continued to work with gulp 4. The gulp-help *package* you referenced is not a plugin and was always a hack on top of our architecture; we've released a feature with gulp 4 that does away with the need for that package.
3. Gulp 4 was published a year ago as a beta and bumped to latest stable a few months ago when we squashed a few bugs.
4. The gulp tean has been more active than ever, if you look at our organization, we maintain almost 60 packages. We're also hosting office hours and helping the community a ton.
4. If you are trying to use an old version of gulp, don't rely on * in your package.json and instead hardcode the actual version you want to use. Note though that you're unlikely to get any help with old versions because the community has moved on.

**Comment by fluffynuts** [comment]
from https://www.npmjs.com/package/gulp:
```
    gulp v4.0.0 - npm install gulp@next
    gulp v4.0.0-alpha.3 - npm install gulpjs/gulp#v4.0.0-alpha.3
    gulp v3.9.1 - npm install gulp
```
(quite clearly states that `npm install gulp` should get me 3.9.1)

However, I'm interested in adopting gulp4 if it is possible -- I don't have some special tie to an older version. Am I right in saying that the `description` part of the `metaData`, as described at https://gulpjs.com/docs/en/api/task#task-metadata replaces the functionality I would have expected from `gulp-help`?

I apologise for (probably) coming off as a little unkind. I'm glad that gulp continues to evolve -- though it _is_ very confusing not to see that reflected at npmjs.org (see version info above and package last published data at https://www.npmjs.com/package/gulp). As someone who isn't inside your organisation, how would you expect to react if suddenly your stuff stopped working and, according to the official package page, it shouldn't have? I guess it was just the last straw in a day where I've been fixing everyone else's problems.

**Comment by phated** [comment]
@fluffynuts unfortunately, npm never released a long-promised feature to allow us to update the README they use for their website unless we republish the whole package with a new semver version.  That's not something we really want to do.

I'm sorry that the npm limitation caused you troubles when you were working on getting gulp installed. You are often better off clicking-through to the project's GitHub page from npm to get updated documentation (like our updated [README](https://github.com/gulpjs/gulp/blob/master/README.md)).  We've also been putting in a ton of effort on our website to have a good user-experience for reading/receiving official docs.

You are correct that task metadata is the way to provide help for your tasks.  You then view the "help" with the `gulp --tasks` command.

**Comment by FJame** [comment]
Hey Guys try this option
with this command: gulp --tasks
system show you list of task that gulp can do it!
name of  pug task for me was 'pug_0'
I hope this comment solve your problem
