### ISSUE TITLE
npx (local) Gulp for Windows 10 fail to generate files

### ISSUE THREAD

**Issue by dtvn** [gulpjs/gulp#2387]
**What were you expecting to happen?**
It supposes to generate files (Js, CSS, and json) then put it in `_pkg` directory. The `_pkg` directory is created in the same level of `gulpfile.js`. The source files are kept in directories which are in the same level of `gulpfile.js` as well. All the path is relative.

**What actually happened?**
Nothing actually happens. It just print a normal log. No error returns. According to gulp-debug, it seems like there is no item was passed to the `src`. But how it couldn't get it is unknown to me.

This bug only happens in **Windows**, and maybe as local version. In **Linux**, as global version, it works a bit better (still have a small bug that causing unable to use `series` and `parallel`, but it at least can generate files correctly)

> [00:11:19] Using gulpfile D:\Sterling\[1] Desktop\desuarchive\gulpfile.js
> [00:11:19] Starting 'js'...
> [00:11:19] gulp-debug: 0 items
> [00:11:19] Finished 'js' after 210 ms

**Sample of my gulpfile**: https://gist.github.com/dtvn/022c35696aa11592991133744a933dff

**My system info**
- gulp  ( CLI v2.2.0 | Local v4.0.2 )
- npm : v6.9.0
- node : v10.16.0

I have read some closed issues in the repo. However, none of it seems like this. Also, this only happens in Window or as a local version, so I guess it could be a bug.

**Comment by uclladt** [comment]
I've also a problem with rename in our script on windows 10.
Using tesame script on windows 8.1 worked well.

`// Javascript minify task
gulp.task('scripts', function() {
  gulp.src(paths.scripts.src)
    .pipe($.plumber())
    .pipe($.uglify())
    .pipe($.rename(function (path) {
      path.basename += ".min";
    }))
    .pipe(gulp.dest(paths.scripts.dest));
});
`

Changing the script by using minify instead of uglify and rename has solved my problem on windows 10.

`// Javascript minify task
gulp.task('scripts', function() {
  gulp.src(paths.scripts.src)
    .pipe($.minify({
      ext: {
        min:'.min.js'
      },
      noSource: true
    }))
    .pipe(gulp.dest(paths.scripts.dest));
});
`

**Comment by sttk** [comment]
@dtvn I could reproduce it. This cause is that glob recognizes `'[1]'` in the path as a pattern of regexp. When I changed the directory to `D:\Sterling Desktop\desuarchive`, that code worked right on windows10. @uclladt's code behaves the same way for such directory names.

The root cause of this problem is that glob-stream passes absolute path of `src` to Glob. By commenting out [this line](https://github.com/gulpjs/glob-stream/blob/master/readable.js#L61), that code worked right even when the directory is `D:\Sterling[1] Desktop\desuarchive`.

@phated Are there any problems with parsing only a relative path in glob-stream?

**Comment by uclladt** [comment]
@sttk i didn't noticed the '[1]' in het path that was the root cause. So i thought that this problem was related to my problem. My mistake.
My problem was that the rename-function wasn't working under windows 10.
And minify resolved it for me.

**Comment by phated** [comment]
@dtvn you can't "reuse" a stream like you are doing with `dest`, that's not how they work.
