### ISSUE TITLE
Prototype Pollution: yargs-parser    

### ISSUE THREAD

**Issue by SidselImer** [gulpjs/gulp#2486]
Is there is any chance of the yargs-parser getting updated? I am asking purely for security issues related to my project. 

 Patched in    │ >=13.1.2 <14.0.0 || >=15.0.1 <16.0.0 || >=18.1.2

**Comment by joaogarin** [comment]
Yes also getting this error. It seems gulp will only be updating this in gulp5 https://github.com/gulpjs/gulp-cli/issues/207 However it is stated here : 

"There is 0 security risk to our users, this is not a real vulnerability vector for a local build tool. Do not run commands on your computer that you didn't write yourself." which sounds like a reasonable advice :P 

Also related https://github.com/gulpjs/gulp-cli/issues/194

Seems the problem is gulp has made the commitment to keep compatibility with Node 0.10 but yargs has essentially dropped support for that and so it can't be upgraded

**Comment by phated** [comment]
We worked with the maintainer of yargs to get the fix to this issue backported. You seem to not have updated your lockfile in a long time or this warning would have gone away.
