### ISSUE TITLE
Issues with glob-parent and yargs-parser

### ISSUE THREAD

**Issue by Joaco0102** [gulpjs/gulp#2611]
Hi, i´m learning to use Gulp and when i install it i get these 3 vulnerabilities:

![glob-parent and yargs-parser issues](https://user-images.githubusercontent.com/59095136/127399915-1b3d2329-81cd-4a4a-ae7f-452fee5e7bc1.png)

I tried updating glob-parent and yargs-parser as that is the solution i found on the internet but i still get these vulnerabilites. I was wondering if anyone could help me or  at least explain me what this means and what should i do. Thank you!

Sorry if i made any mistake in the post, i´m new to git also :)

**Comment by phated** [comment]
https://overreacted.io/npm-audit-broken-by-design/

**Comment by ssmall** [comment]
This is a pretty cheeky response for a project that hasn't had a release in over 2 years. Perhaps instead of gaslighting new users into believing that these aren't real issues (they absolutely could be in some contexts) you could shed some light on when this might be fixed. Or, if gulp is not being actively maintained, perhaps you could put a notice on the repo to that effect so that folks can start looking elsewhere for build tools.
