### ISSUE TITLE
gaze update breaks things

### ISSUE THREAD

**Issue by yocontra** [gulpjs/gulp#416]
- OSes not set up to build native modules (windows, osx stock, some linux)
- process never exits

Post here if anything else was broken.

Temporary solution: `npm install gaze@0.5.x -D`

If it isn't fixed by tomorrow I'll roll it back in glob-watcher and wait until the new gaze is more stable.

Sorry all for the inconvenience, I should have had more tests to catch this.

**Comment by gaearon** [comment]
If anyone reading this still has this issue, double-check your tasks.
Maybe it's a Gulp task and not Gulp itself that is broken for you.

I spent a lot of time hunting this issue until I figured out it was happening due to [gulp-shell needing a Node 0.11 fix](https://github.com/sun-zheng-an/gulp-shell/commit/81d873d4e1f26dcbac8ece13d498a5dffbce458b).

**Comment by gmhenderson** [comment]
Thank you @gaearon for the followup, I was running into the same issue.

**Comment by crispen-smith** [comment]
Not sure if this is related, but I seem to be having issues with sass.watch

This is taken from my console:

Crispens-MacBook-Pro:site crispensmith$ sudo gulp sass
Password:
[23:09:26] Using gulpfile ~/Documents/goal/site/gulpFile.js
[23:09:26] Starting 'sass'...
[23:09:27] Finished 'sass' after 807 ms
Crispens-MacBook-Pro:site crispensmith$ sudo gulp watch
[23:12:06] Using gulpfile ~/Documents/goal/site/gulpFile.js
[23:12:06] Starting 'sass'...
[23:12:07] Finished 'sass' after 867 ms
[23:12:07] Starting 'watch'...
^C^C^C

in order to kill that process I seem to need to close the console window.  If I run browser-sync it also seems to be failing on me.

What confuses me is that this seemed to be working less than 24 hours ago and I don't recall updating any dependancies in the interim.

Here's my gulpfile (it's pretty simple)

/*jslint node:true */
"use strict";

var gulp = require("gulp"),
  sass = require("gulp-sass"),
  browserSync = require("browser-sync"),
  nodemon = require("gulp-nodemon");

gulp.task("test", function () {
  console.log("TEST PASSED");
});

gulp.task("start", function () {
  nodemon({
    script: "node_modules/.bin/lcm",
    args: ["server"],
    nodeArgs: [],
    ext: "js html",
    env: {"NODE_ENV" : "development" }
  });
});

gulp.task("sass", function () {
  return gulp.src('../offsite/sass/**/*.scss')
    .pipe(sass())
    .pipe(gulp.dest("resources/stylesheets"))
    .pipe(browserSync.stream());
});

gulp.task("browserSync", function () {
  browserSync.init({
    proxy: "http://localhost:3000/wireframe/resequenced/second"
  });
});

gulp.task("watch", ["sass"], function () {
  gulp.watch('/**/*.css', ['sass']);
//  gulp.watch('/**/*.html').on("change", browserSync.reload);
//  gulp.watch('/**/*.ejs').on("change", browserSync.reload);
//  gulp.watch('/**/*.js').on("change", browserSync.reload);
});
