### ISSUE TITLE
Document gulp.start()

### ISSUE THREAD

**Issue by binarykitchen** [gulpjs/gulp#505]
I've been searching for docu on how `gulp.start()` works.

I wonder if I can pass on parameters to a new gulp task through that start function?

Also, how can I start another gulp task inside a running gulp task? I mean, can I pipe gulp.start to somewhere else in the middle?

**Comment by moander** [comment]
```js
gulp.task('build', ['clean', 'task1']);
```
dont work because of parallelism.. Dirty solution:
```js
gulp.task('build', ['clean'], function() {
    gulp.start('task1');
});
```

What is the best practice to solve this without having task1 to depend on the clean task?

**Comment by wfayeBerman** [comment]
gulp.start() still works, is it deprecated?  is there a better way to do the following if one is not using gulpfile.js?

    var gulp = require('gulp');

    gulp.task('testing', function() {
	    console.log('test started')
    });

    gulp.task('default', ['testing'])

    gulp.start();

**Comment by Prinzhorn** [comment]
I have the same question as @wfayeBerman . I'll explain my use case because it's an edge case (I'm good at those I guess...).

I want to use gulp from within another node process. The other node process is an express app. An example use case is when someone in the UI hits the "publish" button a POST request to the server is made. Within the request handler I want to run the gulp "publish" task which takes some data from the disk and a database and uploads it to S3. Since gulp does a great job with this task, I don't see a reason not to use gulp or to reinvent the wheel. But I understand that using gulp on something else than a development machine is not the intended use-case, but a viable one.

**Comment by basvandenheuvel** [comment]
No documentation because it's being removed from the code? Looks like it's stil there after 2 years?

**Comment by phated** [comment]
@basvandenheuvel all work is being done in the 4.0 branch.  This is not a supported API and will not be documented.  Locking.
