### ISSUE TITLE
Ability to create new gulpfile.js with `gulp init` command

### ISSUE THREAD

**Issue by mikach** [gulpjs/gulp#58]
The same functionality as grunt-cli provides.

What do you think?

**Comment by webcaetano** [comment]
+1

**Comment by marksomnian** [comment]
> Would conflict with a task named init

Wouldn't you just be able to detect if there is a `Gulpfile.js` in the directory, and if not, then create one, if there is, then run the `init` task?

**Comment by devonzara** [comment]
+1 If the file doesn't exist, create it with a basic template. If it does exist, look for and run the task named init.

**Comment by dvdcxn** [comment]
+1 

I found this page because I was googling to find if gulp just used a different command for its init functionality. 

Imo it's a simple bit of functionality but keeps it consistent with the rest of the node-sphere.

Sre, a basic gulpfile can easily be copy pasted, but it takes a couple of steps which can break the flow when setting up a build environment if doing so manually.

The fact that people have found this page due to expecting "gulp init" to just work is a pretty good argument for including it.

**Comment by contra** [comment]
How about gulp --init?

**Comment by phated** [comment]
This really isn't about a flag, it's that we would be implementing `touch gulpfile.js` because there's no point in putting anything in the file.  Everyone has their own way to structure gulpfiles and that's a great thing.

**Comment by webcaetano** [comment]
@phated Agree. 
But a good part of gulp projects come from an yeoman boilerplate. http://yeoman.io/generators/
This is already an good approach for "init". 

I think this issue are opening for the wrong repository. This should be in [gulp-cli](https://github.com/gulpjs/gulp-cli) instead.

Or even an new node-module `gulp-init` that generate multi gulp boilerplates. 
But i think this may already exist. Not sure.

People think in `gulp init` based on other programs that have one like 
- `git init`
- `npm init`
- `bower init`

**Comment by devonzara** [comment]
Even if it is just a blank file, it would help establish a naming convention. It seems to be agreed upon that package.json and bower.json are all lowercase but with Gulp I often see a variation between Gulpfile.js and gulpfile.js.

Furthermore, even if there isn't really any boilerplate that applies to all projects, you can include some Getting Started information in the file for those who are new to Gulp and links to the docs/recipies.

But yes, `gulp init` would just be a way of complying with expectations or a seemingly unofficial convention brought forth by other commonly used tools. Regardless of how useful it for more experienced users, it's more a matter of being intuitive for those who are familiar but may not work with Gulp everyday.

**Comment by phated** [comment]
@devonzara but gulp isn't convention based, that's the whole point behind it.  We allow people to name it `gulpfile.js` to match their `package.json` or `Gulpfile.js` to mimic Makefiles if the desire.  I've even seen people name a directory `gulpfile` with an `index.js` inside which will also work because of node's require system.  This flexibility is something we want to promote and not have a mandatory or suggested way to name your files.

**Comment by devonzara** [comment]
Fair enough on the naming.

However, there is a big difference between helping newcomers get up and running quickly with a single gulpfile versus making it mandatory. I wasn't aware of these other variations in use, but perhaps that's to be attributed to the fact that you're 'Getting Started' page is already suggesting (or providing as an example) the 'gulpfile.js' way of handling things and doesn't detail any other methods.

I don't see how including a `gulp init` would be any different than what is already mentioned on the 'Getting Started' page. It doesn't take away from the flexibility of Gulp and it's not forcing anyone to use `gulp init` or the single-file route, it just provides a convenience method that is handy to those who are not everyday Gulpers or those who aren't comfortable with OS native commands like `touch gulpfile.js` or `REM. >gulpfile.js`.

**Comment by marksomnian** [comment]
This. So much this.

**Comment by DBassel** [comment]
+1

**Comment by Squidies** [comment]
I actually got to this issue because I wanted to check that `gulp init` **wasn't** already a defined function. The reason being is I want to use `init` as a way to initialize my project such as copy front-end dependencies to respective folders, compile initial sass, etc.

I am in support of a command to create a *limited* gulpfile.js file, but would like to see `init` remain available to roll my own initial gulp install configs.

**Comment by MatheusRV** [comment]
+1
