### ISSUE TITLE
Gulp as a background task

### ISSUE THREAD

**Issue by ilanbiala** [gulpjs/gulp#644]
It would be great to have gulp run as a background task, especially when things like `gulp.watch` are going on, so that users don't have to have so many terminal windows open. I'm not sure if this would have to be implemented per gulp plugin, or through Gulp as a whole. It's just a thought though, and I'm looking to get some ideas on it, if there's a better way to have a server running and `gulp.watch` (or a similar process) running concurrently.

**Comment by johntdowney** [comment]
The only problem I have with `gulp &` is that it stops running if you log out.  Any other similar linuxy solutions?

**Comment by doowb** [comment]
I found that `screen` is a good tool to use for that. I'm not positive on exactly how it works, but I think it creates a new terminal instance to run the process in.

I've been doing something similar to this:

```sh
$ screen -dmSL gulp gulp build
```

This does the following:

- `screen` starts a new terminal screen
- `-dm` forces a new session that is detached (this allows you to log out of the terminal and back in later to reconnect)
- `-S` name the session (this is the first `gulp` above) I was experimenting without this and wasn't getting it to work properly.
- `-L` this logs the output to `screenlog.0`. I'm not sure if this can be changed.

You can check to see if any screens are running by doing `screen -ls`.
You can also reattach to a screen by doing `screen -r` (if there is only one it will attach, otherwise you'll have to provide a name found from doing `screen -ls`.

When reattached, you can do `Ctrl+c` to stop the session. You can also do `Ctrl+a,d` to detach from the session if you want it to keep running.

I've also found that with the command above if you're not running `.watch`, the session will close when the task is finished running. This is useful if it's just a long running task that you want to check up on the progress of through the `screenlog.0` file: `tail -f screenlog.0`

Hope this helps. Also, this can be used for any process that might be long running.
