### ISSUE TITLE
API docs missing gulp.start()

### ISSUE THREAD

**Issue by dman777** [gulpjs/gulp#755]
Unless I am having a off day and missing it, it seems `gulp.start()` is missing from the api docs.

**Comment by justinmchase** [comment]
Start seems like a good api to use in watch tasks. Is there a better way to do this?

```
gulp.task('watch', () => {
  var sources = [...]
  gulp.watch(sources, ['test'])
  gulp.start('test')
})
```

If you put test as a dependency instead of invoke via `gulp.start` then the process will exit if a test fails and watch is never invoked. But this way you will get your tests running immediately but watch will continue to run. This seems like a legitimate enough scenario to add this function to the docs, I had to search for a while to find out how to do this satisfactorily.

**Comment by phated** [comment]
@justinmchase `start` is the only way to do what you want in gulp 3 but it was never officially supported by gulp (it was exposed by a dependency) and is completely gone in gulp 4.  I don't suggest using it.

**Comment by justinmchase** [comment]
how would you do it in gulp 4, for reference?

**Comment by phated** [comment]
@justinmchase everything in gulp 4 is just a function, you just call it

**Comment by justinmchase** [comment]
I see, thanks.

**Comment by felixfbecker** [comment]
> everything in gulp 4 is just a function, you just call it

Is there a way to make Gulp log the standard `Starting 'taskName'`/`Finished 'taskName'` when doing so?

**Comment by demurgos** [comment]
Is your use case related to the watch mode or is it about simply starting the tasks programmatically. There was [a recent issue for this](https://github.com/gulpjs/gulp/issues/2203) that got shut down (simply call the functions, as mentioned above).

The logs are handled at the CLI level. I don't think there's way to trigger them when calling the task function programmatically.

I'd recommend to open a new issue if you want to request this feature instead of replying to an old issue. If this is just a support question, it's better suited for Stack Overflow. (Due to the high number of issues, this tracker is only intended for bugs)

**Comment by felixfbecker** [comment]
It's a watch use case, but when not using `gulp.watch()`, but e.g. webpack's watch API. _After_ the webpack compilation is done I also need to trigger some other tasks.

**Comment by demurgos** [comment]
Seems like a valid use case to me but I am not sure if it is possible currently.
