### ISSUE TITLE
Add recipe for running shell commands

### ISSUE THREAD

**Issue by mnquintana** [gulpjs/gulp#794]
It would be awesome to have a recipe for running shell commands via gulp. I'd make a PR for this myself, but I'm actually not sure what the best practice for this is anymore. Is it [`gulp-exec`](https://github.com/robrich/gulp-exec)? Is it Node's `child_process.exec` or `child_process.spawn`?

Either way, I'd love to get a recipe for this added.

Thanks!

**Comment by backspaces** [comment]
Forgive my noobness, but .. I'm using the gulp-docco plugin which fails to produce docco's navigation menu.  It's default is to create a menu on each file docco converts into html which navigates between the files given to the docco command.

Here's the github issue:  https://github.com/jsBoot/gulp-docco/issues/2  The author of gulp-docco mentioned this problem: 
    Right now, the plugin doesn't support it (because it operates on each file individually, not as a whole).

Is there a way to just run the command "docco -o <dir> <files>" in gulp? Doing this on the command line produces the desired nav menus, but using the docco task in my gulp file does not.

I ask here because it seems to match the issue being raised here.

**Comment by phated** [comment]
I just added this in the 4.0 branch.
