### ISSUE TITLE
Gulp 4 Docs

### ISSUE THREAD

**Issue by demisx** [gulpjs/gulp#803]
We currently use gulp 3 for all our build needs. I'd like to come up to speed on gulp 4 and potentially move some of our projects to it. I have a couple of questions:

1. When is the anticipated release for v4?
2. What's the best place to start reading about v4? I am not sure if docs on 4.0 branch are up to date.

Thanks.

**Comment by johnpapa** [comment]
I'm interested in contributing to this. I'll be releasing a 4+ hour video series in Gulp in late Jan 2015 and would like to help write the v4 docs, migration and more recipes for v4 when its time

**Comment by travm** [comment]
I'll be available to help as well.

**Comment by phated** [comment]
Some places to start:

https://github.com/phated/async-done
https://github.com/phated/undertaker
https://github.com/phated/bach
and the vinyl-* repositories

These docs will need to be translated to gulp-specific docs since gulp4 is built on top of them.

**Comment by contra** [comment]
Yeah, we need help updating the `docs` folder which has become quite the large task. I'm open to seriously trimming down the docs folder to the essentials, reorganizing, redoing entirely, etc. for the gulp release. I will be doing markdown -> html and adding some nice styles to put the docs on the main site. One thing we failed really bad at was putting all the docs in one place (there are so many sub-projects) which I want to address in the 4.0 release.

**Comment by sochka** [comment]
Any updates? Gulp 4.1 according to milestone page should have been released but 4.0 is not released yet.

**Comment by contra** [comment]
@sochka Milestone dates mean nothing, we are busy people - it will get released when it gets released. Use the 4.0 branch until then.

**Comment by phated** [comment]
I do actually have an update.  @dinoboff has been knocking out quite a few of the remaining blockers and I am using 4.0 in my current project to see if I run into any major bugs.  That being said, @contra is right, it will be released when it is ready.  The best thing you can do is use the 4.0 branch and let us know of any problems.

**Comment by contra** [comment]
Also of relevance to this issue: We are working on a new website that will put all of the docs, blogs, guides, tutorials, recipes, etc. from all of the repos across the gulp ecosystem (vinyl, vinyl-fs, glob-watcher, etc.) in one place. The site will be searchable, indexed on google, and pretty badass.

**Comment by callumacrae** [comment]
yay! :smiley:

**Comment by contra** [comment]
If anybody would like to be a part of writing the docs/blogs/guides/whatever for the new site (there is a nice editor page and everything) send an email to contra@wearefractal.com and I'll get you invited as an admin

**Comment by phated** [comment]
I've begun migrating docs to the new website, but I don't have much time to do it.  Please, if you have availability to do this, email @contra

**Comment by torarnek** [comment]
I am looking very much forward to running tasks in parallell. Is it possible to get some kind of alpha release? That would help us starting using it. :)

**Comment by dinoboff** [comment]
```shell
npm install gulpjs/gulp.git#4.0
```
or if you don't want to track the branch, I think you can the commit hash. E.g.:
```shell
npm install gulpjs/gulp.git#b477a4de75
```

**Comment by phated** [comment]
@dinoboff don't suggest the hash because we rebase 4.0 pretty often.

**Comment by demisx** [comment]
@torarnek I've documented Gulp 4 installation instructions here http://demisx.github.io/gulp4/2015/01/15/install-gulp4.html. So far, Gulp 4 has been working great for us and it's been as stable as any production version. Highly recommend.

**Comment by dinoboff** [comment]
@phated fixed :)

**Comment by torarnek** [comment]
@demisx @dinoboff  Thanks, however, in our production builds we are not allowed to link directly to github, it has to be released on NPM so that the packages can be cached in our build environment.

Would it be possible go have an alpha/beta release on npm? :)

**Comment by phated** [comment]
@torarnek sorry, we aren't even close to an npm release.

**Comment by deepsweet** [comment]
but why it can't be published as alpha version(s)?

**Comment by callumacrae** [comment]
Because you typically don't publish alpha releases until you've at least finished all your features. As you can install from github, there is also no need for development releases.

You're expecting the developers to put in extra for work for absolutely no gain for them—time they could spend working on Gulp 4 itself.

Just install from github. You shouldn't be running dev code on production anyway, so there shouldn't be any restrictions on where you can install from.

**Comment by troch** [comment]
@contra, @phated I have recently started a series of articles that is a [tour of main Node-based building tools](http://blog.reactandbethankful.com/posts/2015/04/18/tour-of-node-building-tools/): Grunt, Gulp and Broccoli (and will probably talk about other solutions like metalsmith). The Gulp part made me dig quite a bit because of Gulp 4 and I have came up with 4 articles, plus a "how to install" and a new gulp plugin for incremental builds called [gulp-memory-cache](https://github.com/troch/gulp-memory-cache):

- [How to install Gulp 4](http://blog.reactandbethankful.com/posts/2015/05/01/how-to-install-gulp-4/)
- [Part 1: examples](http://blog.reactandbethankful.com/posts/2015/04/23/building-with-gulp-3-and-4-part-1-examples/)
- [Part 2: Gulp's anatomy](http://blog.reactandbethankful.com/posts/2015/04/23/building-with-gulp-3-and-4-part-2-gulp-anatomy/)
- [Part 3: writing transformers](http://blog.reactandbethankful.com/posts/2015/04/28/building-with-gulp-3-and-4-part-3-writing-transformers/)
- [Part 4: incremental builds](http://blog.reactandbethankful.com/posts/2015/05/01/building-with-gulp-4-part-4-incremental-builds/)

There is a mix of Gulp 3 and 4: Parts 1, 2 and 3 talk about both and Part 4 focuses on Gulp 4. For that reason I don't think articles can be reused as-is but if you are interested in any of the above, I am happy to contribute or for anyone to reuse. English is not my native language so my grammar and syntax are not up there, that's the only limitation :-)

**Comment by phated** [comment]
I believe the gulp4 docs are very good now.  Also, we can open individual issues for anything we feel is missing.  Going to close this.

**Comment by xtianus79** [comment]
Where are the docs located?

**Comment by xtianus79** [comment]
I found this and the fix at the bottom might have been the fix... http://blog.reactandbethankful.com/posts/2015/05/01/how-to-install-gulp-4/

**Comment by sameeri** [comment]
@xtianus79  and anyone who has difficulty looking for docs (gulp 4) right now and you have hit this issue looking around.

* https://github.com/gulpjs/gulp/blob/4.0/docs/API.md
* https://github.com/gulpjs/gulp-cli/tree/4.0/docs

Also, please look at the issues labeled documentation combined together with gulp 4 to understand the team's plan for docs. 

* https://github.com/gulpjs/gulp/labels/documentation

Also, something cool to know : gulp 4 docs will be on gitbook, according to the team's plans.

**Comment by EricBou** [comment]
Actually I have some problem to use gulp v4.0 on github(firewall and security problem)

Someone planning to make gulp version 4.x available on NPM soon?
