### ISSUE TITLE
Gulp.src should be a passthrough

### ISSUE THREAD

**Issue by contra** [gulpjs/gulp#840]
https://github.com/wearefractal/vinyl-fs/issues/25

**Comment by josiahsprague** [comment]
I've been struggling with this for the past few days. I had the following gulp task, where I was using `gulp.src` to add files to an existing stream, based on [the release notes for 3.8.0](https://github.com/gulpjs/gulp/releases/tag/3.8). At first it appeared to be working, but then I noticed that only two of the files I was adding were in the final output, rather than all five.

```
var gulp = require('gulp');
var concat = require('gulp-concat');
var source = require('vinyl-source-stream');
var buffer = require('vinyl-buffer');
var browserify = require('browserify');
var hbsfy = require('hbsfy');
var uglifyify = require('uglifyify');
 
var browserifyEntries = ['/path/to/commonJS-index.js'];
var legacyScripts = [
  '/path/to/script1.js',
  '/path/to/script2.js',
  '/path/to/script3.js',
  '/path/to/script4.js',
  '/path/to/script5.js',
];
 
gulp.task('compile-js', function(){
  var browserified = browserify({entries: browserifyEntries})
  .transform(hbsfy)
  .transform(uglifyify)
  .bundle();
 
  browserified
    .pipe(source('browserified.js'))
    .pipe(gulp.src(legacyScripts))
    .pipe(buffer())
    .pipe(concat('scripts.js'))
    .pipe(gulp.dest('./assets/compiled/')); //Output only contains browserified.js, script1.js, and script2.js
});
```

My current solution is to just use `gulp-add-src` and replace the `gulp.src()` call with that. Would be nice to use `gulp.src` though.

**Comment by contra** [comment]
@josiahsprague I would love a PR from the `gulp-add-src` people to fix this, I just haven't had time to look at it

**Comment by contra** [comment]
Nobody wants to take a swing at this so we can land it in gulp 4?

**Comment by UltCombo** [comment]
@contra what's the spec for this functionality? AFAICS `gulp.src` (or, more specifically, `glob-stream`) filters out vinyl files [whose paths have already went through the stream](https://github.com/wearefractal/glob-stream/blob/6411ea4891d24227f94f302bd52d79584af8fa9b/index.js#L97).
So what would be the expected behavior here in case of a vinyl fine being piped into a `gulp.src` stream which would produce a vinyl file with the same path? Should it only emit one? If so, which?

**Comment by contra** [comment]
@UltCombo Same behavior as vinyl-add-src

**Comment by kevva** [comment]
Could someone tell me the steps to reproduce this properly and you'll have an PR for it later today.

**Comment by heikki** [comment]
@kevva I have example here: https://github.com/heikki/gulp-src-debug/blob/master/gulpfile.js

**Comment by nfroidure** [comment]
I think this problem looks like the one described here https://github.com/sindresorhus/gulp-filter/issues/29

`gulp.src` should be a PassThrough stream *only* if you ask it to be so since the above bug description need to wait for the passthrough stream to be ended before ending himself.

I suggest this API:

```
gulp.src('**/*', { passtrough: true })
```

As a temporary fix, you could look at this attempt:
https://github.com/sindresorhus/gulp-filter/pull/35

**Comment by UltCombo** [comment]
+1 for `{ passtrough: true }`, that way the implementation doesn't have to rely on hacks such as listening for `pipe` events.

**Comment by contra** [comment]
@UltCombo I'm +1 or `passthrough: true` to be more explicit

**Comment by UltCombo** [comment]
@contra not sure if I understand. Do you want `passthrough` to be more explicit? As in `{ duplex: true }`?

**Comment by contra** [comment]
@UltCombo I am +1 on a passthrough option because it makes this feature more explicit.

**Comment by UltCombo** [comment]
Oh ok, I was unsure whether you were ok with this approach or if you wanted to be more explicit than the suggested. `=]`

I believe it shouldn't be too hard to implement the `passthrough` option then.

**Comment by UltCombo** [comment]
wearefractal/vinyl-fs#55

**Comment by contra** [comment]
@UltCombo Nice - looking forward to merging that one tonight. Closing this, will be in gulp 4.0 (via vinyl-fs 4.0)
