### ISSUE TITLE
Update gulp recipe to include browserify transform

### ISSUE THREAD

**Issue by kevinsimper** [gulpjs/gulp#989]
RIght now if you add a transform to the browserify recipe that is in this repository you will get a "write after end".

https://github.com/gulpjs/gulp/blob/master/docs/recipes/browserify-uglify-sourcemap.md

I do not know the exact cause, but it seems to be a problem that many have a hard time solving.
https://twitter.com/ph1/status/550014199544705024
https://github.com/substack/node-browserify/issues/1044
https://gist.github.com/moredip/14f69be3a45e11b2a36d

How is this solved best?

**Comment by phated** [comment]
Typically when you are combining browserify and gulp, you use gulp plugins to handle things that browserify transforms would typically be used for (like gulp-react or gulp-babel instead of the reactify transform).  However, I am going to try to debug this right now and see if I can find anything.

**Comment by phated** [comment]
It turns out that browserify doesn't work with transforms (or very well, at all) when constructed inside a stream.  I am not sure why this is or what changed in recent releases.  However, I was able to get a working example and I've created a recipe for working with browserify and transforms at https://github.com/gulpjs/gulp/blob/master/docs/recipes/browserify-transforms.md.  I also updated our browserify + uglify example to move the browserify instance construction outside of the stream.

**Comment by jmm** [comment]
@phated

> Typically when you are combining browserify and gulp, you use gulp plugins to handle things that browserify transforms would typically be used for

You have to use browserify transforms for things you need to do to the dependencies as opposed to entry file(s).

> It turns out that browserify doesn't work with transforms (or very well, at all) when constructed inside a stream. I am not sure why this is or what changed in recent releases.

It's like I explained here: https://github.com/gulpjs/gulp/issues/970#issuecomment-85005200 and https://github.com/substack/node-browserify/issues/1044#issuecomment-68783570.

This is a misapplication of vinyl-transform, which is designed to wrap a transform stream. `browserify().bundle()` does not return a transform stream. This only works by accident when the timing works out so that the `bundle()` stream is unpiped before vinyl-transform's `from` stream attempts to write to it. Prior to browserify 8.0.2, registering a transform function, e.g. `browserify().transform(some_func)`, was a synchronous operation. In 8.0.2 it became async (nextTick'd). So before 8.0.2, the "writable" side of the `bundle()` stream is already ended when vinyl-transform pipes to it, which I guess results in it being unpiped before being written to. As of 8.0.2 the `.transform()` call is still pending so the "writable" side of the `bundle()` stream isn't ended yet when vinyl-transform sets up the pipe, but then browserify ends it when it's done with it, and I guess it's written to before being unpiped.

Even the revised version of this recipe doesn't allow you to do very much: a single entry file and no gulp content transformation plugins between `gulp.src()` and browserify (it might as well be `gulp.src(..., {read: false})`). What's better about this than?:

```js
browserify('one', 'two', ...)
  .transform(whatever)
  .bundle()
  .pipe(require('vinyl-source-stream')('whatever'))
  ...
```
